config/routes.rb
Rails.application.routes.draw do
  root to: "cars#index"

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :users

  resources :cars, except: %I[index] do
    resources :bookings, only: %I[new create]
  end
  resources :bookings, only: %I[show index destroy]

  resources :profiles, only: %I[show destroy] do
    get "/cars", to: "profiles#cars", as: :cars
    get "/my_bookings", to: "profiles#my_bookings", as: :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, :end_date, presence: true
  validates :start_date, :end_date, uniqueness: true
  validate :end_date_after_start_date
  validates :start_date, :end_date, overlap: { scope: 'car_id',
                                               message_content: 'overlaps with this cars other bookings.' }

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many_attached :photos
  validates :model, :price, :seat_number, :description, :address, :photos, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search,
                  against: %i[model price seat_number address description],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
  has_many :booked_cars, through: :bookings
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %I[show destroy]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
    @booking.car = @car
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.car = @car

    if @booking.save
      redirect_to new_car_booking_path, notice: "Booking was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @booking.destroy
    redirect_to profile_bookings_path(current_user.id)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %I[show edit update]

  def index
    @cars = Car.all
    @cars = Car.search(params[:query]) if params[:query].present?
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @markers = [{
              lat: @car.latitude,
              lng: @car.longitude
    }]
  end

  def edit; end

  def update
    @car.update(update_car_params)
    @car.photos.concat(params[:photos]) unless params[:photos].nil?
    if @car.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:model, :price, :seat_number, :address, :description, :latitude, :longitude, photos: [])
  end

  def update_car_params
    params.require(:car).permit(:model, :price, :seat_number, :address, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show; end

  def cars
    @cars = current_user.cars
  end

  def my_bookings; end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to profile_cars_path(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<section class= "body">
 <div class="card col-6 shadow-lg p-3 mb-5 bg-white rounded" style="width: 50rem; margin: auto; border-radius: 5px;">
  <div class="card-body" data-controller="toggle" data-toggle-price-value="<%= @booking.car.price %>">
    <h2>Book your Car</h2>
    <%= simple_form_for [@car, @booking] do |f| %>
      <%= f.input :start_date , as: :string,
        input_html: { data: { controller: "datepicker", action: "change->toggle#setStartDate" } } %>
      <%= f.input :end_date, as: :string,
        input_html: { data: { controller: "datepicker", action: "change->toggle#setEndDate" } } %>
      <p class= "d-none" data-toggle-target="priceText"></p>
      <div class="d-flex justify-content-between">
        <%= f.submit %>
      </div>
    <% end %>
</div>

</section>

app/views/bookings/new.html.erb
<div>
  <%= render "form", booking: @booking %>
</div>

app/views/cars/_form.html.erb
<div>
<%= simple_form_for(car) do |f| %>
  <%= f.input :model %>
  <%= f.input :price %>
  <%= f.input :seat_number %>
  <%= f.input :address %>
  <%= f.input :description, :as => :text, :input_html => { 'rows' => 7} %>
  <% if car.persisted? %>
    <%= f.input :photos, as: :file,
          input_html: { multiple: true },
          hint:"Don't upload if you aren't adding photos",
          required: false %>
    <% else %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <% end %>

  <div class="center-button">
    <%= f.submit class:"button-2"%>
  </div>
<% end %>
</div>

app/views/cars/edit.html.erb
<div class="card col-6 shadow-lg p-3 mb-5 bg-white rounded" style="width: 50rem; margin: auto; border-radius: 5px;">
  <div class="card-body ">
  <h1 class="text-center">Edit your <%= @car.model %></h1>
<%= render "form", car: @car %>
  </div>
</div>

app/views/cars/index.html.erb
<section class="text-center " >
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_url "background-large.jpg" %>');">
    <h1 class= "jumbotron-heading">Search Less. Live More.</h1>
    <p class="lead text-muted">We make finding the right car simple.</p>
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: root_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "What you are looking for?"
          %>
          <%= submit_tag "Search Now", name: "", class: "button-1" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="cardpage">
    <h1 class="texttitle">All cars for Rent</h1>
    <div class="showbigcards">
      <% @cars.each do |car| %>
        <div class="showsmallcards">
          <%= cl_image_tag car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
          <p><strong><%= car.model %></strong></p>
          <div class="cardtext">
            <p class="cardprice"><b>Price:</b> €<%= car.price %></p>
            <p><b>Capacity:</b> <%= car.seat_number %></p>
          </div>
          <%= link_to "See Offer", car_path(car.id), class:"button-2" %>
        </div>
      <% end %>
    <div>
  </div>
</section>

app/views/cars/new.html.erb
<div class="card col-6 shadow-lg p-3 mb-5 mt-5 bg-white" style="width: 50rem; margin: auto; border-radius: 5px;">
  <div class="text-center modify-text ">
    <h1>Add here your new car</h1>
  </div>
  <%= render "form", car: @car %>
</div>

app/views/cars/show.html.erb
<div>
  <div class="show-tables">
    <div class="pictures-carousel">
      <div id="carouselExampleControls" class="col d-flex carousel slide resize-css" data-ride="carousel">
        <div class="carousel-inner">
          <% @car.photos.each_with_index do |photo, i| %>
          <div class="carousel-item <%= 'active' if i == 0 %>">
            <%= cl_image_tag photo.key, crop: :fill, style:"width: 100%" %>
          </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class="about-content">
      <div class="share-save">
        <i class="fa-regular fa-share-from-square " style="color: #050505;"></i>
        <%= link_to "Share this car", root_path, class:"text-decoration-none"  %>
        <i class="fa-regular fa-heart  " style="color: #000000;"></i>
        <%= link_to "Save this car",root_path, class:"text-decoration-none"%>
      </div>

      <div>
        <h1><%= @car.model %></h1>
        <p> Address: <%= @car.address %></p>
      </div>
      <div>
        <p>Price for <b>€<%= @car.price%></b> a day !! </p>
        <p>Car for <%= @car.seat_number %> peoples</p>
      </div>
      <div class="car-description">
        <h4>Car description</h4>
        <p><%= @car.description %></p>
        <div class="buttons-show">
          <% if (current_user != @car.user) %>
            <%= link_to "Book this car", new_car_booking_path(@car.id), class:"button-2"  %>
          <% end %>
          <%= link_to "View All Car for Rent", root_path, class:"button-2"   %>
        </div>
      </div>
    </div>

  </div>

  <div class="map-position">
    <div class="col map-style" style="width: 100%; height: 300px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

<%# Alerts %>
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 Free cancellation up to 48 hours before pick-up.</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer justify-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2023 Copyright: WorkSmart <i class="fas fa-heart"></i>
  </div>
</div>

app/views/layouts/_navbar.html.erb
  <nav class="cardpage navbar sticky-top navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <p class="navbar-brandcss-nav" style="margin: 10px">SmartRBnB</p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:"nav-link css-nav", style:"margin-left: 20px" %>
      </li>
    </ul>
  </div>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in?  %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle css-nav " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account Settings
          </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdown">
          <%= link_to "Add a Car", new_car_path, class:"dropdown-item css-nav " %>
          <%= link_to "Edit Account", edit_user_registration_path, class:"dropdown-item css-nav"  %>
          <%= link_to "View profile", profile_path(current_user.id), class:"dropdown-item css-nav" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign out", destroy_user_session_path, class:"dropdown-item css-nav", style:"border: none;"%>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log-in", user_session_path, class:"nav-link css-nav"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%# Bootstrap and JS %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%# Flatpickr %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css">
    <%# Geocoder %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="cardpage">
    <%= render "layouts/flashes" %>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>


<%# Font awesome %>
  <script src="https://kit.fontawesome.com/eb1bfde2de.js" crossorigin="anonymous"></script>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/cars.html.erb
<section>
  <div class="cardpage">
    <h1 class="texttitle text-center">All <%= current_user.first_name %>'s cars</h1>
    <div class="showbigcards">
      <% @cars.each do |car| %>
        <div class="showsmallcards">
          <%= cl_image_tag car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
          <p><strong><%= car.model %></strong></p>
          <div class="cardtext">
            <p class="cardprice"><b>Price:</b> €<%= car.price %></p>
            <p><b>Capacity:</b> <%= car.seat_number %></p>
          </div>

          <div class="button-prifile-car">
            <%= link_to "See Offer", car_path(car.id), class:"button-2" %>
            <%= link_to "Edit", edit_car_path(car.id), class:"button-2" %>
            <%= link_to "Delete",
              profile_path(car.id),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class:"button-3"
            %>
          </div>

        </div>
      <% end %>
    <div>
  </div>
</section>

app/views/profiles/my_bookings.html.erb
<section>
  <div class="cardpage">
    <h1 class="texttitle text-center">All <%= current_user.first_name %>'s bookings</h1>
    <div class="showbigcards">
      <% current_user.bookings.each do |booking| %>
        <div class="showsmallcards">
          <%= cl_image_tag booking.car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
          <div class="booking-text">
            <strong>Booking Starts:</strong>
            <%= booking.start_date %>
            <strong>Booking Ends:</strong>
            <%= booking.end_date %>
            <strong>Car Owner:</strong>
            <%= booking.car.user.first_name %>
            <%= booking.car.user.last_name %>
          </div>

          <div class="button-my-bookings">
            <%= link_to "View", car_path(booking.car.id), class:"button-2"%>
            <%= link_to "Delete",
              booking_path(booking.id),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class:"button-3"
            %>
          </div>
        </div>
      <% end %>
    <div>
  </div>
</section>

app/views/profiles/show.html.erb
<div>
  <h1 class="text-center mt-3"><%= current_user.first_name %> <%= current_user.last_name %>'s profile</h1>
  <div class="row justify-content-center">
    <div class="col-10 showsmallcards">
      <h2 class="text-center">Account Details</h2>
      <div class="d-flex justify-content-around">
        <p><strong>Email:</strong> <%= current_user.email %></p>
        <p><strong>Number of bookings:</strong> <%= current_user.bookings.count %></p>
        <p><strong>Number of cars:</strong><%= current_user.cars.count %></p>
      </div>
    </div>

    <div class="col-10 showsmallcards">
      <h2 class="text-center"><%= link_to "My Cars", profile_cars_path(current_user.id), class:"text-decoration-none text-reset"%></h2>
        <% if current_user.cars.first != nil%>
          <div class="bigcards justify-content-around">
              <% current_user.cars.first(2).each do |car| %>
                <div class="showsmallcards">
                  <%= cl_image_tag car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
                  <p><strong><%= car.model %></strong></p>
                  <div class="cardtext">
                    <p class="cardprice"><b>Price:</b> €<%= car.price %></p>
                    <p><b>Capacity:</b> <%= car.seat_number %></p>
                  </div>
                </div>
              <% end %>
          </div>
        <% else %>
          <div class="d-flex justify-content-center">
            <p class="text-center">You currently haven't registered a car</p>
          </div>
        <% end %>
    </div>

    <div class="col-10 showsmallcards">
      <h2 class="text-center"><%= link_to "Cars booked by me", profile_bookings_path(current_user.id), class:"text-decoration-none text-reset"%></h2>
        <% if current_user.bookings.first != nil %>
          <div class="showbigcards d-flex justify-content-around">
            <% current_user.bookings.first(2).each do |booking| %>
              <div class="showsmallcards">
                <%= cl_image_tag booking.car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
                <p><strong><%= booking.car.model %></strong></p>
                <div class="cardtext">
                  <p class="cardprice"><b>Price:</b> €<%= booking.car.price %></p>
                  <p><b>Capacity:</b> <%= booking.car.seat_number %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="d-flex justify-content-center">
            <p> You don't have any booked cars</p>
          </div>
        <% end %>
    </div>

    <div class="col-10 showsmallcards">
      <h2 class="text-center">My cars booked by other users</h2>
        <% if current_user.cars.first != nil %>
          <% if current_user.cars.first.bookings.first != nil %>
            <div class="bigcards justify-content-around">
              <% current_user.cars.first(2).each do |car| %>
                <% car.bookings.first(2).each do |booking| %>
                  <div class="showsmallcards">
                      <%= cl_image_tag booking.car.photos.first.key, height: 180, width: 280, crop: :fill, class:"carimage"%>
                    <p><strong><%= booking.car.model %></strong></p>
                    <div class="cardtext">
                      <p class="cardprice"><b>Price:</b> €<%= booking.car.price %></p>
                      <p><b>Capacity:</b> <%= booking.car.seat_number %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="d-flex justify-content-center">
            <p class="text-center">None of your cars currently have bookings</p>
          </div>
        <% end %>
    </div>
  </div>
</div>